export default {
  USER: {
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_TOKEN_UPDATE: 'USER_TOKEN_UPDATE',
    USER_UPDATE: 'USER_UPDATE'
  },
  PRAYERS: {
    PRAYERS_UPDATE: 'PRAYERS_UPDATE'
  },
  INTENTIONS: {
    INTENTIONS_UPDATE: 'INTENTIONS_UPDATE',
    INTENTIONS_ADD: 'INTENTIONS_ADD',
    INTENTIONS_REMOVE: 'INTENTIONS_REMOVE'
  },
  FAVOURITES: {
    FAVOURITES_ADD: 'FAV_ADD',
    FAVOURITES_UPDATE: 'FAV_UPDATE',
    FAVOURITES_DELETE: 'FAV_DELETE'
  },
  EVANGILE: {
    EVAN_UPDATE: 'EVANGILE_UPDATE'
  },
  DAILY_INFOS: {
    UPDATE_INFOS: 'DAILY_INFOS_UPDATE'
  }
}
